name: bench
on: [push, pull_request]

jobs:

  benchmarks:
    name: Check Benchmarks Compilation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'
          cache: true

      - name: Compile benchmarks
        run: go test -bench=. -benchtime=100x -count=5 -benchmem -run=^$ -v ./...
